baseURL = 'http://Biscue5.github.io'
languageCode = 'en-us'
title = 'biscue'
theme = 'ananke'
publishDir = 'docs'

params:
  biscue_socials:
    -name: twitter 
    url: https://twitter.com
    label: TND Twitter
