baseURL = "https://biscue5.github.io"
languageCode = "en-us"
theme = "aafu"

publishDir = "docs"

[build]
  writeStats = true

[params]
    title = "Aafu theme"
    author = "Tomoya Yoshida"
    description = "Biscue homepage"
    #copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    #[params.favicons]
    #    use = true
    #    metas = '''
    #    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    #    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    #   <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    #   <link rel="manifest" href="site.webmanifest">
    #    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
    #   <link rel="shortcut icon" href="favicon.ico">
    #    '''

    # Profile section
    [params.profile]
        name = "Tomoya Yoshida"
        #tagline = "Master thesis"
        location = "M.S. student"
        photo = "dog.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/Biscue5"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/Biscue_510"
            title = "Twitter"
        #[[params.social.list]]
        #    icon = "ai ai-google-scholar"
        #    url = "#"
        #    title = "Google Scholar"
        #[[params.social.list]]
        #    icon = "fab fa-researchgate"
        #    url = "#"
        #    title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    #[[params.showInAccordion]]
    #    item = "project"
    #[[params.showInAccordion]]
    #    item = "skill"


    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I am ..."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        #[[params.experience.list]]
        #    position = "Job Title"
        #    dates = "2018 - 2019"
        #    url = "#"
        #    company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        #[[params.education.list]]
        #    degree = "Ph.D. in Subject"
        #    college = "University of State-City"
        #    dates = "2013 - 2018"
        #    thesis_title = "Effect of humans on other humans: a study of human behavior."
        #    thesis_url = "#"
        [[params.education.list]]
            degree = "M.S. in Informatics"
            college = "Kyoto University"
            dates = "2022 - 2024"
        [[params.education.list]]
            degree = "B.S. of Multi-Interdisciplinary Engineering"
            college = "The University of Electro-Communications"
            dates = "2018 - 2022"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Conference"]

        [[params.publication.list]]
            title = "単語の階層関係に基づくデータ拡張を利用した画像キャプション生成の検討"
            authors = "吉田智哉, 西村太一, 亀甲博貴, 森信介"
            date = "2023"
            journal = "言語処理学会第29回年次大会 (NLP2023)"
            url = "https://www.anlp.jp/proceedings/annual_meeting/2023/pdf_dir/P2-1.pdf"
            type = "Conference"

    # Project section
    #[params.project]
        #title = "Projects"
        #icon = "fas fa-project-diagram"

        #[[params.project.list]]
        #    title = "Project 1"
        #    url = "#"
        #    description = "Description of the project"

    # Skill section
    #[params.skill]
    #    title = "Skills"
    #    panelId = "skill-panel"
    #    icon = "fas fa-cogs"

    #   [[params.skill.list]]
    #        skill = "Skill 1, Skill 2"
    #        skillrating = 90

