baseURL = 'http://Biscue5.github.io'
languageCode = 'en-us'
title = 'biscue'
theme = 'ananke'
publishDir = 'docs'

[author]
  name = "Biscue"
  bio = "Hello, there"
  location = "Japan"
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
